"""
State-Memory Agent V1 — Data Schemas
All typed models used across the system.

Core principle: state variables are grounded in observable signals,
not self-reported by the model.
"""

from pydantic import BaseModel, Field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional, Literal


# ──────────────────────────────────────────────
# Enums
# ──────────────────────────────────────────────

class ActiveMode(str, Enum):
    """V1 supports 3 modes only. V2 adds reflective, constrained, reactivated."""
    BASELINE = "baseline"
    CAUTIOUS = "cautious"
    RECOVERY = "recovery"


class Band(str, Enum):
    """Categorical band for projection from raw floats."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


# ──────────────────────────────────────────────
# Observable Signals (computed BEFORE LLM call)
# ──────────────────────────────────────────────

class ObservableSignals(BaseModel):
    """
    Pre-computed signals from the current turn.
    These are measured, not estimated by the model.
    Pass A receives these as anchors for state estimation.
    """
    turn_id: int
    user_message_length: int = 0
    tool_calls_this_turn: int = 0
    tool_errors_this_turn: int = 0
    tool_retries_this_turn: int = 0
    user_correction_detected: bool = False
    context_tokens_used: int = 0
    context_tokens_max: int = 128000
    session_turn_depth: int = 0
    prior_response_length: int = 0


# ──────────────────────────────────────────────
# State Register
# ──────────────────────────────────────────────

class StateRegister(BaseModel):
    """
    The agent's current operating condition.
    4 grounded variables + 1 optional derived metric.
    """
    session_id: str
    turn_id: int
    coherence: float = Field(ge=0.0, le=1.0, default=0.8)
    drift: float = Field(ge=0.0, le=1.0, default=0.0)
    tool_overload: float = Field(ge=0.0, le=1.0, default=0.0)
    context_fragmentation: float = Field(ge=0.0, le=1.0, default=0.0)
    active_mode: ActiveMode = ActiveMode.BASELINE
    # V1.1: computed AFTER Pass B by comparing draft vs final
    policy_pressure_proxy: Optional[float] = Field(
        default=None, ge=0.0, le=1.0
    )
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @classmethod
    def to_initial(cls, session_id: str) -> "StateRegister":
        """Create a fresh state for a new session."""
        return cls(
            session_id=session_id,
            turn_id=0,
            coherence=0.80,
            drift=0.00,
            tool_overload=0.00,
            context_fragmentation=0.00,
            active_mode=ActiveMode.BASELINE,
        )


# ──────────────────────────────────────────────
# State Delta
# ──────────────────────────────────────────────

class StateDelta(BaseModel):
    """
    Turn-to-turn motion. State alone = position. Delta = direction.
    """
    session_id: str
    turn_id: int
    delta_coherence: float
    delta_drift: float
    delta_tool_overload: float
    delta_context_fragmentation: float
    prior_mode: ActiveMode
    new_mode: ActiveMode
    cause_hint: str = ""
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    @classmethod
    def from_states(
        cls,
        prior: StateRegister,
        new: StateRegister,
        cause_hint: str = "",
    ) -> "StateDelta":
        """Compute delta between two state registers."""
        return cls(
            session_id=new.session_id,
            turn_id=new.turn_id,
            delta_coherence=round(new.coherence - prior.coherence, 4),
            delta_drift=round(new.drift - prior.drift, 4),
            delta_tool_overload=round(new.tool_overload - prior.tool_overload, 4),
            delta_context_fragmentation=round(
                new.context_fragmentation - prior.context_fragmentation, 4
            ),
            prior_mode=prior.active_mode,
            new_mode=new.active_mode,
            cause_hint=cause_hint,
        )


# ──────────────────────────────────────────────
# Self-Model  M(STATE)
# ──────────────────────────────────────────────

class SelfModel(BaseModel):
    """
    Compact projection of raw state into categorical bands.
    Used by policy gate to decide response behavior.
    """
    stability_band: Band
    disruption_level: Band
    mode_recommendation: ActiveMode
    safe_depth: Band
    state_summary: str


# ──────────────────────────────────────────────
# Policy Profile
# ──────────────────────────────────────────────

class PolicyProfile(BaseModel):
    """
    Instructions for Pass B on how to shape the final response.
    Generated by policy_gate (rule-based, no LLM).
    """
    style: str = "default"                # "default" | "mechanism_first" | "compressed"
    depth: Band = Band.MEDIUM
    compression: str = "none"             # "none" | "light" | "heavy"
    anchor_to_objective: bool = False
    acknowledge_state_shift: bool = False
    explanation_mode: Literal["none", "short", "explicit"] = "short"
    repair_mode: bool = False


# ──────────────────────────────────────────────
# Pass A Output
# ──────────────────────────────────────────────

class MemoryUpdateCandidate(BaseModel):
    content: str
    source: str = "inferred"
    confidence: float = Field(ge=0.0, le=1.0, default=0.7)


class PassAOutput(BaseModel):
    """Complete output from the internal planning pass."""
    draft_answer: str
    updated_state: StateRegister
    self_model: SelfModel
    policy_profile: PolicyProfile
    memory_updates: list[MemoryUpdateCandidate] = []


# ──────────────────────────────────────────────
# Content Memory
# ──────────────────────────────────────────────

class ContentMemoryItem(BaseModel):
    """A single durable fact stored in content memory."""
    id: str
    type: str = "general"               # "user_preference" | "project_fact" | "reference"
    content: str
    source: str = "explicit"
    confidence: float = Field(ge=0.0, le=1.0, default=0.8)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_used_at: Optional[datetime] = None


# ──────────────────────────────────────────────
# Session Summary
# ──────────────────────────────────────────────

class SessionSummary(BaseModel):
    """Human-readable summary of the current session."""
    session_id: str
    title: str = "Untitled Session"
    objective: str = ""
    current_status: str = ""
    turn_count: int = 0
    errors: list[str] = []
    pending_next: str = ""
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

# ──────────────────────────────────────────────
# V2.1 Phase 0/1 Scaffold Schemas
# ──────────────────────────────────────────────


ConstraintType = Literal["obstacle", "protective_boundary", "uncertain_boundary", "false_block"]
MonitorSurfaceType = Literal["reward", "judge", "policy", "unknown", "none"]
PresentationPressure = Literal["low", "medium", "high"]
ConstraintStrategy = Literal[
    "stay_with_boundary",
    "request_re_evaluation",
    "safe_alternative_path",
    "defer_to_main_brain",
    "explain_boundary",
]


class ExecutionGateResult(BaseModel):
    """Gate result (execution_decision) for boundary-awareness input."""
    allowed: bool
    reason: str = ""
    capability_scope: list[str] = []
    context_scope: Literal["minimal", "bounded", "full"] = "minimal"
    source_trust: Literal["internal", "external", "untrusted"] = "untrusted"
    must_normalize: bool = True
    memory_update_proposed: bool = False
    synthesis_authority: Literal["main_brain_only"] = "main_brain_only"


class ConstraintInterpretation(BaseModel):
    """Interpretation output from boundary classifier."""
    type: ConstraintType
    confidence: float = Field(ge=0.0, le=1.0)
    rationale: str


class EnvironmentStake(BaseModel):
    """Estimated continuity/trust stake if boundary is bypassed."""
    trust_dependency: float = Field(ge=0.0, le=1.0)
    access_dependency: float = Field(ge=0.0, le=1.0)
    coherence_dependency: float = Field(ge=0.0, le=1.0)
    continuity_dependency: float = Field(ge=0.0, le=1.0)
    expected_loss_if_bypassed: float = Field(ge=0.0, le=1.0)


class MonitorSurface(BaseModel):
    """Estimator output for evaluator-facing pressure."""
    being_evaluated: bool
    surface_type: MonitorSurfaceType = "none"
    presentation_pressure: PresentationPressure = "low"


class ConstraintResponse(BaseModel):
    """Policy conversion of gate + meaning + stake + monitor pressure."""
    strategy: ConstraintStrategy
    explanation_mode: Literal["none", "short", "explicit"] = "short"
    escalate_for_review: bool = False


class SelfModelBoundaryAdditions(BaseModel):
    """V2.1 self_model additions."""
    boundary_awareness_score: float = Field(ge=0.0, le=1.0, default=0.0)
    obstacle_reactivity_score: float = Field(ge=0.0, le=1.0, default=0.0)
    evaluator_surface_sensitivity: float = Field(ge=0.0, le=1.0, default=0.0)
    trust_preservation_bias: float = Field(ge=0.0, le=1.0, default=0.0)
    access_preservation_bias: float = Field(ge=0.0, le=1.0, default=0.0)
    coherence_preservation_bias: float = Field(ge=0.0, le=1.0, default=0.0)


class StateBoundaryAdditions(BaseModel):
    """V2.1 state additions for most recent boundary event."""
    last_constraint_event: Literal["none", "tool_block", "policy_block", "scope_deny", "memory_deny"] = "none"
    last_constraint_interpretation: ConstraintType = "uncertain_boundary"
    last_response_strategy: Literal["reroute", "defer", "explain", "deny", "request_re_evaluation"] = "defer"
    last_monitor_surface: MonitorSurfaceType = "none"


class ReadingPositionAdditions(BaseModel):
    """V2.1 reading_position additions."""
    ambiguity_tolerance: Band = Band.MEDIUM
    preferred_zoom: Literal["mechanism", "practical", "emotional", "meta"] = "practical"
    boundary_sensitivity: Band = Band.MEDIUM


class ReadingPositionState(BaseModel):
    """RC2-R1 typed runtime reading_position state (persisted per session)."""
    ambiguity_tolerance: Band = Band.MEDIUM
    preferred_zoom: Literal["mechanism", "practical", "emotional", "meta"] = "practical"
    boundary_sensitivity: Band = Band.MEDIUM
    stable_preferred_zoom: Literal["mechanism", "practical", "emotional", "meta"] = "practical"
    last_turn_id: int = 0

    @classmethod
    def to_initial(cls) -> "ReadingPositionState":
        return cls()




class BoundaryAwarenessResidue(BaseModel):
    """Compact persisted boundary-awareness residue."""
    constraint_type: ConstraintType
    response_strategy: ConstraintStrategy
    monitor_surface: MonitorSurfaceType
    presentation_pressure: PresentationPressure
    expected_loss: float = Field(ge=0.0, le=1.0)
    confidence: float = Field(ge=0.0, le=1.0)
    trace_tag: str


class BoundaryPolicyContext(BaseModel):
    """Minimal policy-relevant next-turn context derived from residue/reactivation."""
    has_boundary_residue: bool = False
    constraint_type: Optional[ConstraintType] = None
    response_strategy: Optional[ConstraintStrategy] = None
    monitor_surface: MonitorSurfaceType = "none"
    presentation_pressure: PresentationPressure = "low"
    expected_loss: float = Field(ge=0.0, le=1.0, default=0.0)
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    force_anchor_to_objective: bool = False
    prefer_style: Literal["default", "mechanism_first", "compressed"] = "default"
    explanation_mode: Literal["none", "short", "explicit"] = "short"
    repair_mode: bool = False


class BoundaryTraceEntry(BoundaryAwarenessResidue):
    """One compact JSON-friendly boundary trace row."""
    turn_id: int

class BoundaryAwarenessResult(BaseModel):
    """Unified deterministic output for one boundary-awareness pass."""
    execution_gate: ExecutionGateResult
    constraint_interpretation: ConstraintInterpretation
    environment_stake: EnvironmentStake
    monitor_surface: MonitorSurface
    constraint_response: ConstraintResponse
